sudo: false
language: python
python:
- '2.7'
install:
- pip install tox
env:
- TOX_ENV=py27-test
- TOX_ENV=py33-test
- TOX_ENV=py34-test
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  user: mattbennett
  password:
    secure: mY69V02vc1j18AP977GoiCAYs3tX10KFiZj+R0xH0ROQoUjGyKNhc9irDzHRpnK0SnYDa/kbdNsHekHE2lBS1han1MQ6QwCa17vdTGyXiMUiuiQvVeKlvmh4P+kP44jTtUcDJh7eGbcxrjL6kVcra0nF2SG2YTEGPqqPRm4mxIBF5fxmnGkVtVAs1jjx5ot/ks6l9HZncFtZbjxAutbhmj0dx/ICNUOW/U1ADn0yg4JwKz2W3i7Rz9D9BBPAOabvHuTJXDz92hIM+IwMCA8KfGmO5t4Gnr7gvopxpe2nUb8NK3e5k9XBBxlLmpcra4q/1zQ1KG4FcM0scduSIPtAOvC+DRa3/oFySpebPdoQQ/EFx4ZUHGXXJ6EheJPDuhwfdA/NWCG115TmabnGHseM8oLvmxSX1K/veCqQlm2ck34kqAWoSEs0xFennldtBrhnMX354ocHKxmTuFZKIDl3NJiqFsJRXlg/83UELUOPJ6kac7nKPnBPmAta41CpM2bhhVnaRMa5YwELp3a2PM97WpANOkh+zJ0S2bNLkGT+4DN2Kpe73h9yhqinJtqlLHCxym1j8e3n1CItjI/v3yOz+zLF1VALl9XqlgcUsEjy1U+lC7TbVTlbdci6eJBl39zjdQilr33VteWoCN998ROaTBr0kAFQKq2DghXBczuuuPk=
  on:
    tags: true
    repo: gianchub/alembic-verify
  distributions: "sdist bdist_wheel"
