"""initial

Revision ID: 3070a2ba5acc
Revises:
Create Date: 2025-12-03 15:26:26.670482

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3070a2ba5acc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=True),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("ssn", sa.Unicode(length=30), nullable=False),
        sa.Column("number_of_pets", sa.Integer(), nullable=False),
        sa.Column(
            "title", sa.Enum("ENGINEER", "MANAGER", "DIRECTOR", "CEO", name="title"), nullable=True
        ),
        sa.Column(
            "department",
            sa.Enum("Product", "Engineering", "Sales", native_enum=False),
            nullable=True,
        ),
        sa.CheckConstraint("age > 0 AND age <= 100", name="check_age"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_name"), "employees", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_name"), table_name="employees")
    op.drop_table("employees")
    op.execute("DROP TYPE IF EXISTS title")
    # ### end Alembic commands ###
