"""Add is_mobile column to mobile_numbers table

Revision ID: 44352f0a4052
Revises: 591a8001cae9
Create Date: 2026-01-14 16:13:22.519646

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "44352f0a4052"
down_revision = "591a8001cae9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mobile_numbers",
        sa.Column("is_mobile", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobile_numbers", "is_mobile")
    # ### end Alembic commands ###
