"""add skills and mobile numbers

Revision ID: 591a8001cae9
Revises: 9182e2f9745a
Create Date: 2025-12-03 15:34:24.262011

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "591a8001cae9"
down_revision = "9182e2f9745a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mobile_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Mobile numbers are the mobile numbers of the employees",
    )
    op.create_table(
        "skills",
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Unicode(length=100), nullable=True),
        sa.Column("employee", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee"], ["employees.id"], name="fk_skills_employees"),
        sa.PrimaryKeyConstraint("slug"),
        comment="Skills are the skills of the employees",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skills")
    op.drop_table("mobile_numbers")
    # ### end Alembic commands ###
