"""Add company

Revision ID: 6c4a48d80d8a
Revises: 3070a2ba5acc
Create Date: 2025-12-03 15:30:05.622062

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6c4a48d80d8a"
down_revision = "3070a2ba5acc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("employees", sa.Column("company_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_employees_companies", "employees", "companies", ["company_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_employees_companies", "employees", type_="foreignkey")
    op.drop_column("employees", "company_id")
    op.drop_table("companies")
    # ### end Alembic commands ###
