"""add role

Revision ID: 9182e2f9745a
Revises: 6c4a48d80d8a
Create Date: 2025-12-03 15:32:57.050326

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9182e2f9745a"
down_revision = "6c4a48d80d8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=50), nullable=False),
        sa.Column("role_type", sa.Enum("Permanent", "Contractor", name="role_type"), nullable=True),
        sa.CheckConstraint("LENGTH(name) > 5", name="check_name"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("employees", sa.Column("role_id", sa.Integer(), nullable=False))
    op.create_foreign_key("fk_employees_roles", "employees", "roles", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_employees_roles", "employees", type_="foreignkey")
    op.drop_column("employees", "role_id")
    op.drop_table("roles")
    op.execute("DROP TYPE IF EXISTS role_type")
    # ### end Alembic commands ###
