"""empty message

Revision ID: 9331f5cd7f8a
Revises: 591a8001cae9
Create Date: 2026-01-21 15:07:50.249494

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9331f5cd7f8a"
down_revision = "591a8001cae9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mobile_numbers", sa.Column("is_landline", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobile_numbers", "is_landline")
    # ### end Alembic commands ###
